title: Alexander Weissman # your name (or website title) here
logo: "/images/Alex Weissman.png ?raw=true" # your photo (or logo) here
description: |
  CFA level 2 candidate and Student at Lehigh University studying Finance and Economics
  <br>
  
  <br><br>
  <a href="https://www.linkedin.com/in/alexander-weissman-49b391207/">LinkedIn</a> 
  <br>
  <a href="images/ACW___Resume MAC CFA.pdf" target="_blank">Resume</a>      
  <br>
  <a href="https://github.com/acw224-15/">GitHub</a>  
  <br>
  <a href="mailto:alexandercw15@gmail.com"" target="_blank">Email</a> 

theme: jekyll-theme-minimal
