title: Alexander Weissman # your name (or website title) here
logo: "/images/Alex Weissman.png ?raw=true" # your photo (or logo) here
description: |
  Student at Lehigh University studying Finance and Economics
  <br>
  
  <br><br>
  <a href="https://www.linkedin.com/in/alexander-weissman-49b391207/">LinkedIn</a> 
  <br>
  <a href="output_18_0.pngResume</a>   
  <br>
  <a href="https://github.com/acw224-15/">GitHub</a>  
  <br>
  <a href="excel_work.html" target="_blank">Excel Work</a> <!-- This link will open the excel_work.html page in a new tab -->

theme: jekyll-theme-minimal
